version: "3.8"

services:
  app:
    image: 1201q/interview:latest
    container_name: interview
    restart: always
    expose:
      - "8000"
    networks:
      - app-network
    env_file:
      - .env
    environment:
      - TZ=Asia/Seoul
    platform: linux/arm64
  ml-server:
    build:
      context: ./ml-server
      dockerfile: Dockerfile
    container_name: ml-server
    restart: always
    networks:
      - app-network
    env_file:
      - ./ml-server/.env
    ports:
      - "5000:5000"
    platform: linux/arm64

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
    networks:
      - app-network
    environment:
      - TZ=Asia/Seoul
    platform: linux/arm64
  redis:
    image: redis:latest
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - app-network
    platform: linux/arm64

networks:
  app-network:
    driver: bridge
